name: RetroBlock
version: '${project.version}'
main: fr.delmath.RetroBlock
api-version: '1.13'
commands:
  wand:
    description: recuperer la wand de selection de zone
    usage: /<command>
  select:
    description: selectioner une zone
    usage: /<command> <location 1> <location 2>
  history:
    description: recuperer l'historique de la zone
    usage: /<command> <option>
  back:
    description: fait revenir en arrière la zone selectioner
    usage: /<command> <option> <delta>